version: "3.9"

services:
  database:
    image: postgres
    environment:
      - POSTGRES_DB=randsense
      - POSTGRES_USER=randsense
      - POSTGRES_PASSWORD=randsense
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file: env.local
  manage:
    build: .
    entrypoint: /usr/local/bin/python /app/manage.py
    command: shell_plus
    volumes:
      - .:/app
    depends_on:
      - database
    env_file: env.local
  tests:
    build:
      context: .
    depends_on:
      - database
    entrypoint: pytest
    restart: 'no'
    volumes:
      - ./:/app
    env_file: env.tests
