# Generated by Django 3.2.6 on 2021-08-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randsense', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjective',
            options={'ordering': ['base']},
        ),
        migrations.AlterModelOptions(
            name='adverb',
            options={'ordering': ['base']},
        ),
        migrations.AlterModelOptions(
            name='auxiliary',
            options={'ordering': ['base']},
        ),
        migrations.AlterModelOptions(
            name='conjunction',
            options={'ordering': ['base']},
        ),
        migrations.AlterModelOptions(
            name='determiner',
            options={'ordering': ['base']},
        ),
        migrations.AlterModelOptions(
            name='genericword',
            options={'ordering': ['base']},
        ),
        migrations.AlterModelOptions(
            name='modal',
            options={'ordering': ['base']},
        ),
        migrations.AlterModelOptions(
            name='noun',
            options={'ordering': ['base']},
        ),
        migrations.AlterModelOptions(
            name='preposition',
            options={'ordering': ['base']},
        ),
        migrations.AlterModelOptions(
            name='pronoun',
            options={'ordering': ['base']},
        ),
        migrations.AlterModelOptions(
            name='specialword',
            options={'ordering': ['base']},
        ),
        migrations.AlterModelOptions(
            name='verb',
            options={'ordering': ['base']},
        ),
        migrations.AddField(
            model_name='adjective',
            name='rank',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adverb',
            name='rank',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auxiliary',
            name='rank',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conjunction',
            name='rank',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='determiner',
            name='rank',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='genericword',
            name='rank',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modal',
            name='rank',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='noun',
            name='rank',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preposition',
            name='rank',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pronoun',
            name='rank',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specialword',
            name='rank',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verb',
            name='rank',
            field=models.BigIntegerField(default=0),
        ),
    ]
