# Generated by Django 3.1.5 on 2021-01-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randsense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=255)),
                ('category', models.CharField(db_index=True, max_length=255)),
                ('inflections', models.JSONField(blank=True, default=dict)),
                ('attributes', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-base'],
                'abstract': False,
            },
        ),
    ]
