# Generated by Django 3.1.4 on 2021-01-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randsense', '0002_auto_20210103_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='attributes',
            field=models.JSONField(default=dict),
        ),
    ]
