# Generated by Django 3.2.6 on 2021-08-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("randsense", "0002_auto_20210806_0143"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentence",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
