# Generated by Django 3.1.5 on 2021-01-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randsense', '0002_specialword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='base',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
