# Generated by Django 3.1.4 on 2021-01-04 02:38

from django.db import migrations, models
import randsense.models


class Migration(migrations.Migration):

    dependencies = [
        ('randsense', '0003_auto_20210103_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='attributes',
        ),
        migrations.AddField(
            model_name='word',
            name='data',
            field=models.JSONField(default=randsense.models.default_data_json),
        ),
    ]
