# Generated by Django 3.2.6 on 2021-08-06 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randsense', '0003_sentence_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='active',
        ),
        migrations.AddField(
            model_name='adjective',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adverb',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auxiliary',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conjunction',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='determiner',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='genericword',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='modal',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='noun',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='preposition',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pronoun',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='specialword',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='verb',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
