# Generated by Django 3.1.4 on 2021-01-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randsense', '0004_auto_20210104_0238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['-base']},
        ),
        migrations.AddField(
            model_name='sentence',
            name='diagram',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentence',
            name='inflected',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='base',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('base', 'category')},
        ),
    ]
