# Generated by Django 3.2.6 on 2021-08-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("randsense", "0005_apisettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apisettings",
            options={"verbose_name_plural": "API Settings"},
        ),
        migrations.AddField(
            model_name="apisettings",
            name="grammar",
            field=models.TextField(
                blank=True,
                default={
                    "ADJ": [["ADJ", "adj"], ["adj"]],
                    "DETERMINER": [["det"]],
                    "IND-CLAUSE": [["NP", "VP"]],
                    "N": [["ADJ", "noun"], ["noun"]],
                    "NP": [["DETERMINER", "N"], ["DETERMINER", "ADJ", "N"]],
                    "S": [["IND-CLAUSE"]],
                    "VP": [
                        ["verb:intran"],
                        ["verb:tran", "N"],
                        ["verb:tran", "NP"],
                        ["verb:link", "N"],
                    ],
                },
                null=True,
            ),
        ),
    ]
