# Generated by Django 3.1.4 on 2021-01-04 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randsense', '0005_auto_20210104_0612'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=set(),
        ),
    ]
