# Generated by Django 3.1.4 on 2021-01-04 06:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randsense', '0006_auto_20210104_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='diagram',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None),
        ),
    ]
