# Generated by Django 3.2.6 on 2021-08-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("randsense", "0006_auto_20210807_2031"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apisettings",
            name="grammar",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
