# Generated by Django 3.2.6 on 2021-08-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("randsense", "0007_alter_apisettings_grammar"),
    ]

    operations = [
        migrations.AddField(
            model_name="apisettings",
            name="grammar_source",
            field=models.TextField(blank=True, null=True),
        ),
    ]
