# Generated by Django 3.2.6 on 2021-08-09 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randsense', '0008_apisettings_grammar_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='sentence',
            name='incorrect_votes',
            field=models.IntegerField(default=0),
        ),
    ]
