# Generated by Django 3.2.6 on 2021-08-12 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randsense', '0009_auto_20210809_0417'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequencySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nouns', models.BigIntegerField(default=1000000)),
                ('verbs', models.BigIntegerField(default=500000)),
                ('adjectives', models.BigIntegerField(default=500000)),
            ],
            options={
                'verbose_name_plural': 'Frequency Settings',
            },
        ),
        migrations.RemoveField(
            model_name='apisettings',
            name='base_word_frequency',
        ),
        migrations.AddField(
            model_name='apisettings',
            name='frequency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='randsense.frequencysettings'),
        ),
    ]
