# Generated by Django 3.2.6 on 2021-08-12 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('randsense', '0010_auto_20210812_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apisettings',
            name='frequency',
        ),
        migrations.AddField(
            model_name='frequencysettings',
            name='api_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='randsense.apisettings'),
        ),
    ]
