# Generated by Django 3.2.6 on 2021-08-13 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randsense', '0013_frequencysettings_adverbs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequencysettings',
            old_name='adjectives',
            new_name='adjective',
        ),
        migrations.RenameField(
            model_name='frequencysettings',
            old_name='adverbs',
            new_name='adverb',
        ),
        migrations.RenameField(
            model_name='frequencysettings',
            old_name='nouns',
            new_name='noun',
        ),
        migrations.RenameField(
            model_name='frequencysettings',
            old_name='verbs',
            new_name='verb',
        ),
    ]
