# Generated by Django 3.2.6 on 2021-08-13 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('randsense', '0014_auto_20210813_0316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequencysettings',
            old_name='adjective',
            new_name='adj',
        ),
        migrations.RenameField(
            model_name='frequencysettings',
            old_name='adverb',
            new_name='adv',
        ),
    ]
