# Generated by Django 3.2.6 on 2021-08-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('randsense', '0015_auto_20210813_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjective',
            name='removal_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adverb',
            name='removal_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auxiliary',
            name='removal_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conjunction',
            name='removal_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='determiner',
            name='removal_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='genericword',
            name='removal_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modal',
            name='removal_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='noun',
            name='removal_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='preposition',
            name='removal_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pronoun',
            name='removal_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specialword',
            name='removal_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='verb',
            name='removal_votes',
            field=models.IntegerField(default=0),
        ),
    ]
